### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by skhizerabass** [safetysystemtechnology/audio-recorder-button#4]
If you don't hold the button and just tap. It throws exception which is not handled . Can you please review this error.

**Comment by netodevel** [comment]
@skhizerabass thanks, i will fixed this.

**Comment by skhizerabass** [comment]
you made something very great please fix it soon.

**Comment by phonggus** [comment]
If you don't hold the button and just tap. It throws exception which is not handled . Can you please review this error.

**Comment by netodevel** [comment]
@skhizerabass and @phonggus 
update the dependecy for v1.3
` compile 'com.github.safetysystemtechnology:audio-recorder-button:v1.3'`
