### ISSUE TITLE
Android resource compilation failed

### ISSUE THREAD

**Issue by captdantas** [safetysystemtechnology/audio-recorder-button#9]
When attempting to compile an .apk, an error occurs during resource merge.

Checking the error shown, you can find this line: `<item name = "layoutCron" type = "id"> 1 </item>`

According to the Android website, https://developer.android.com/guide/topics/resources/more-resources#Id, the resource of type item should be empty, example: `<item type = "id" name = "id_name" />`

Tested on:
Android Studio 3.4.1
Sdk 28
Build Tools 28.0.3

Reference:
https://stackoverflow.com/questions/52076491/android-inner-element-must-either-be-a-resource-reference-or-empty/52077501

**Comment by eric-diniz** [comment]
That's right, thank you for pointing that out @captdantas
